In [2]:
import numpy as np

In [34]:
a=np.array([[1,2,5,4,3],[5,8,4,6,2]])
b=np.pad(a,((2,2),(0,0)),'constant')
print a[0][0:0+4]

[1 2 5 4]


In [3]:
ddd=np.array([[[1,2,3,4],[5,2,8,4]],[[7,5,4,1],[9,5,1,2]],[[9,5,4,8],[5,1,2,0]]])
print ddd, ddd.shape

[[[1 2 3 4]
  [5 2 8 4]]

 [[7 5 4 1]
  [9 5 1 2]]

 [[9 5 4 8]
  [5 1 2 0]]] (3, 2, 4)


In [10]:
print np.mean(ddd,axis=0)

[[ 5.66666667  4.          3.66666667  4.33333333]
 [ 6.33333333  2.66666667  3.66666667  2.        ]]


In [35]:
print max(dd)

[[7 5 4 1]
 [9 5 1 2]]
