In [1]:
import numpy as np;
print range(5,0,-1)

[5, 4, 3, 2, 1]


In [2]:
print np.zeros([2,3])

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [3]:
print np.zeros(5)

[ 0.  0.  0.  0.  0.]


In [4]:
aa=np.array([[1,2,3],[4,2,5],[6,5,8]])
np.add.at(aa,[[0,1],[1,0]],[2,3])
print aa


[[1 4 3]
 [7 2 5]
 [6 5 8]]


In [9]:
print aa.argmax(axis=1)

[1 0 2]


In [11]:
aa=aa.reshape([1,9])
print aa

[[1 4 3 7 2 5 6 5 8]]


In [13]:
print aa[:,1:3]

[[4 3]]


In [29]:
a=np.array([[1,2]])
b=np.array([[3,4]])
c=np.array([[5,6]])
print np.concatenate((a,b,c,a),axis=1)

[[1 2 3 4 5 6 1 2]]


In [30]:
print range(5,1,-1)

[5, 4, 3, 2]
